# Generated by Django 3.2.13 on 2022-06-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitterapp', '0002_pendingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
