# Generated by Django 3.2.13 on 2022-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitterapp', '0003_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
